# Top-level Gitlab Continuous Integration Config File for exciting
#
# Notes
# ---------
# For all builds:
#   The make.inc is a build stage artifact so the test framework can determine the compiler.
#   An ENV variable is not used, because this would require setting each time the test
#   suite is also used locally.

stages:
  - build
  - python
  - test

# Split configurations into separate files
include:
  - local: '/.gitlab/python-libs.yml'
  - local: '/.gitlab/docs.yml'
  - local: '/.gitlab/exciting-debian-buster-gcc8-serial.yml'
  - local: '/.gitlab/exciting-debian-buster-gcc8-smp.yml'
  - local: '/.gitlab/exciting-debian-buster-gcc8-openmpi3-mpismp.yml'
  - local: '/.gitlab/jupyter-exciting-python-3.7-gcc8-smp.yml'
  # - local: '/.gitlab/exciting-sirius.yml' Alex. Temporarily disable sirius to enable all features to be merged
  - local: '/.gitlab/exciting-debian-buster-intel2019-serial.yml'
  - local: '/.gitlab/exciting-debian-buster-intel2019-smp.yml'
  - local: '/.gitlab/exciting-debian-buster-intel2019-mpismp.yml'
  # Not run as there are simply not enough runners to turn the CI over
  #- local: '/.gitlab/exciting-debian-buster-intel2021-mpismp.yml'
